#!/bin/sh

# Build Haddock documentation and upload it to Hackage manually.
# Necessary because Haddock cannot build docs for this project due
# to the C library dependency.

# Usage:
# Invoke from project root directory.
# $1 is the version number.

if [ $# -ne 1 ]; then
    echo "You must provide exactly one argument."
    echo "That argument is the version number."
    exit 1
fi

cabal configure --user -O0
cabal build
cabal haddock --hyperlink-source

cd dist/doc/html
mv deka deka-$1-docs

tar -cvz -Hustar -f deka-$1-docs.tar.gz deka-$1-docs

curl -u OmariNorman -X PUT -H 'Content-Type: application/x-tar' \
    -H 'Content-Encoding: gzip' --data-binary \
    "@deka-$1-docs.tar.gz" \
    "http://hackage.haskell.org/package/deka-$1/docs"
