-- | Documentation for Deka.
--
-- At the moment, documentation is scattered about.  Some of it is
-- in the main README.md, which is in the source code tree and is
-- viewable in Github at
--
-- <http://github.com/massysett/deka/blob/master/README.md>
--
-- Of course much of it is in the Haddock comments in the source
-- code itself.
--
-- There is also a module here, "Data.Deka.Docs.Examples".  It is in
-- literate Haskell and has many comments.  Unfortunately Haddock
-- does not play well with Literate Haskell.  However, the style of
-- the file would not play well with Haddock anyway so I'm not sure
-- I would ever switch back to regular Haskell for that file.
--
-- So if you link to the file from the Haddock docs, you will just
-- get a blank page.  Fortunately it is easily readable in Github:
--
-- <http://github.com/massysett/deka/blob/master/lib/Data/Deka/Docs/Examples.hs>

module Deka.Docs where
